#include <iostream>
#include "clsPasajeros.h"
#include "clsMenu.h"
using namespace std;

/**
UN SISTEMA DE GESTION DE VIAJES INTERESTELARES ALMACENA LA SIGUIENTE INFORMACION PARA SUS PASAJEROS, CAPITAN, VIAJES Y DESTINOS:

PASAJEROS:
-ID INTERGALACTICO.
-NOMBRE Y APELLIDO.
-FECHA DE NACIMIENTO.
-NIVEL DE CIUDADANIA (1 - CIUDADANO, 2 - MIEMBRO DEL CONSEJO GALACTICO, 3 - EMBAJADOR).

CAPITAN:
-ID INTERGALACTICO.
-NOMBRE Y APELLIDO.
-FECHA DE NACIMIENTO.
-RANGO(1 - NOVATO, 2 - EXPERIMENTADO, 3 - VETERANO).

VIAJES:
-ID DEL VIAJE.
-ID DE CAPITAN.
-ID DE DESTINO.
-TIEMPO DE VIAJE.

DESTINOS:
-ID DE DESTINO.
-NOMBRE DEL PLANETA DE DESTINO.
-DISTANCIA DESDE LA TERMINAL DE SALIDA (EN ANIOS LUZ).

AGREGAR LOS ARCHIVOS Y LOS CAMPOS QUE CONSIDERE NECESARIOS PARA LA GESTION DE LOS VIAJES.

AGREGAR UNA SECCION DE REPORTES QUE SERA COMPLETADA EN LA FASE 3.

REPORTES:

FACIL
-LISTAR PARA CADA VIAJE LA CANTIDAD DE PASAJEROS QUE TUVO ESE VIAJE.
-LISTAR LA CANTIDAD DE VIAJES DE LOS CAPITANES DE RANGO VETERANO


INTERMEDIO
-LISTAR EL MES CON MAYOR CANTIDAD DE PASAJES VENDIDOS ENTRE TODOS LOS ANIOS

DIFICL
-LISTAR EL DESTINO MAS VISITADO
-LISTAR LOS CAPITANES QUE TENGAN VIAJES CUYO NOMBRE DE PLANETA DE DESTINO SE INGRESA POR TECLADO
*/

int main(){

    Menu menu;
    menu.iniciar();
    return 0;
}
