#include <iostream>
#include "clsPasajeros.h"
#include "clsMenu.h"
using namespace std;

/**
UN SISTEMA DE GESTION DE VIAJES INTERESTELARES ALMACENA LA SIGUIENTE INFORMACION PARA SUS PASAJEROS, CAPITAN, VIAJES Y DESTINOS:

PASAJEROS:
-ID INTERGALACTICO.
-NOMBRE Y APELLIDO.
-FECHA DE NACIMIENTO.
-NIVEL DE CIUDADANIA (1 - CIUDADANO, 2 - MIEMBRO DEL CONSEJO GALACTICO, 3 - EMBAJADOR).

CAPITAN:
-ID INTERGALACTICO.
-NOMBRE Y APELLIDO.
-FECHA DE NACIMIENTO.
-RANGO(1 - NOVATO, 2 - EXPERIMENTADO, 3 - VETERANO).

VIAJES:
-ID DEL VIAJE.
-ID DE CAPITAN.
-ID DE DESTINO.
-TIEMPO DE VIAJE.

DESTINOS:
-ID DE DESTINO.
-NOMBRE DEL PLANETA DE DESTINO.
-DISTANCIA DESDE LA TERMINAL DE SALIDA (EN ANIOS LUZ).

AGREGAR LOS ARCHIVOS Y LOS CAMPOS QUE CONSIDERE NECESARIOS PARA LA GESTION DE LOS VIAJES.
*/

int main(){

    Menu menu;
    menu.iniciar();
    return 0;
}
